-- MySQL Script generated by MySQL Workbench
-- Mon Nov 17 21:47:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`versao_schema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`versao_schema` (
  `id_versao` SMALLINT NULL DEFAULT NULL AUTO_INCREMENT,
  `versao` VARCHAR(20) NOT NULL,
  `data_aplicacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_versao`),
  UNIQUE INDEX (`versao` ASC) VISIBLE)
COMMENT = 'Controle de versões do schema do banco de dados';


-- -----------------------------------------------------
-- Table `mydb`.`algoritmo_cripto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`algoritmo_cripto` (
  `id_algoritmo` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_algoritmo` VARCHAR(50) NOT NULL,
  `forca_bits` SMALLINT NOT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `data_implementacao` DATE NOT NULL,
  PRIMARY KEY (`id_algoritmo`),
  UNIQUE INDEX (`nome_algoritmo` ASC) VISIBLE)
COMMENT = 'Catálogo de algoritmos de criptografia utilizados';


-- -----------------------------------------------------
-- Table `mydb`.`tipo_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_acesso` (
  `id_tipo_acesso` SMALLINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_acesso`),
  UNIQUE INDEX (`nome_tipo` ASC) VISIBLE)
COMMENT = 'Tipos de acesso ao sistema (login, logout, falha, etc)';


-- -----------------------------------------------------
-- Table `mydb`.`categoria_log_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria_log_sistema` (
  `id_categoria` SMALLINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX (`nome_categoria` ASC) VISIBLE)
COMMENT = 'Categorias de logs do sistema';


-- -----------------------------------------------------
-- Table `mydb`.`tipo_log_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_log_sistema` (
  `id_tipo_log` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo_log`),
  UNIQUE INDEX (`nome_tipo` ASC) VISIBLE)
COMMENT = 'Tipos de log (INFO, WARNING, ERROR, CRITICAL)';


-- -----------------------------------------------------
-- Table `mydb`.`tipo_operacao_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_operacao_auditoria` (
  `id_tipo_operacao` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_operacao` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_tipo_operacao`),
  UNIQUE INDEX (`nome_operacao` ASC) VISIBLE)
COMMENT = 'Tipos de operações auditáveis (INSERT, UPDATE, DELETE, SELECT)';


-- -----------------------------------------------------
-- Table `mydb`.`tabela_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tabela_sistema` (
  `id_tabela` SMALLINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_tabela` VARCHAR(100) NOT NULL,
  `sensivel_lgpd` TINYINT NULL DEFAULT FALSE,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tabela`),
  UNIQUE INDEX (`nome_tabela` ASC) VISIBLE)
COMMENT = 'Catálogo de tabelas do sistema para auditoria';


-- -----------------------------------------------------
-- Table `mydb`.`status_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status_aluno` (
  `id_status_aluno` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_status` VARCHAR(30) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_status_aluno`),
  UNIQUE INDEX (`nome_status` ASC) VISIBLE)
COMMENT = 'Catálogo de status possíveis para alunos';


-- -----------------------------------------------------
-- Table `mydb`.`status_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status_usuario` (
  `id_status` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_status` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_status`),
  UNIQUE INDEX (`nome_status` ASC) VISIBLE)
COMMENT = 'Catálogo de status de usuários do sistema';


-- -----------------------------------------------------
-- Table `mydb`.`status_pulseira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status_pulseira` (
  `id_status_pulseira` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_status` VARCHAR(30) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_status_pulseira`),
  UNIQUE INDEX (`nome_status` ASC) VISIBLE)
COMMENT = 'Catálogo de status possíveis para pulseiras';


-- -----------------------------------------------------
-- Table `mydb`.`tipo_restricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_restricao` (
  `id_tipo_restricao` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(50) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tipo_restricao`),
  UNIQUE INDEX (`nome_tipo` ASC) VISIBLE)
COMMENT = 'Catálogo de tipos de restrições médicas';


-- -----------------------------------------------------
-- Table `mydb`.`gravidade_restricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gravidade_restricao` (
  `id_gravidade` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(20) NOT NULL,
  `ordem_prioridade` TINYINT NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_gravidade`),
  UNIQUE INDEX (`nivel` ASC) VISIBLE,
  UNIQUE INDEX (`ordem_prioridade` ASC) VISIBLE)
COMMENT = 'Catálogo de níveis de gravidade de restrições médicas';


-- -----------------------------------------------------
-- Table `mydb`.`tipo_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_treino` (
  `id_tipo_treino` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(50) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tipo_treino`),
  UNIQUE INDEX (`nome_tipo` ASC) VISIBLE)
COMMENT = 'Catálogo de tipos de treino disponíveis';


-- -----------------------------------------------------
-- Table `mydb`.`modelo_pulseira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo_pulseira` (
  `id_modelo_pulseira` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_modelo` VARCHAR(100) NOT NULL,
  `fabricante` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `especificacoes_tecnicas` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_modelo_pulseira`),
  UNIQUE INDEX (`nome_modelo` ASC) VISIBLE)
COMMENT = 'Catálogo de modelos de pulseiras inteligentes';


-- -----------------------------------------------------
-- Table `mydb`.`tipo_plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_plano` (
  `id_tipo_plano` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(50) NOT NULL,
  `duracao_dias` INT NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tipo_plano`),
  UNIQUE INDEX (`nome_tipo` ASC) VISIBLE)
COMMENT = 'Catálogo de tipos de planos por duração';


-- -----------------------------------------------------
-- Table `mydb`.`tipo_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_contato` (
  `id_tipo_contato` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_contato`),
  UNIQUE INDEX (`nome_tipo` ASC) VISIBLE)
COMMENT = 'Tipos de contato (email, telefone, celular, etc)';


-- -----------------------------------------------------
-- Table `mydb`.`perfil_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil_acesso` (
  `id_perfil_acesso` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_perfil` VARCHAR(50) NOT NULL,
  `descricao_perfil` VARCHAR(255) NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_perfil_acesso`),
  UNIQUE INDEX (`nome_perfil` ASC) VISIBLE)
COMMENT = 'Perfis de acesso ao sistema (Admin, Instrutor, Recepção, etc)';


-- -----------------------------------------------------
-- Table `mydb`.`permissao_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissao_perfil` (
  `id_permissao_perfil` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `perfil_acesso_id` INT NOT NULL,
  `modulo` VARCHAR(50) NOT NULL,
  `acao` VARCHAR(20) NOT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_permissao_perfil`),
  UNIQUE INDEX `uk_permissao_perfil` (`perfil_acesso_id` ASC, `modulo` ASC, `acao` ASC) VISIBLE,
  INDEX `idx_permissao_perfil` (`perfil_acesso_id` ASC) VISIBLE,
  INDEX `idx_permissao_modulo` (`modulo` ASC) VISIBLE,
  INDEX `fk_permissao_perfil` (`perfil_acesso_id` ASC) VISIBLE,
  CONSTRAINT `fk_permissao_perfil`
    FOREIGN KEY (`perfil_acesso_id`)
    REFERENCES `mydb`.`perfil_acesso` (`id_perfil_acesso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = 'Permissões granulares por perfil de acesso';


-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `id_pessoa` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(99) NOT NULL,
  `cpf_hash` CHAR(64) NOT NULL COMMENT 'Hash SHA-256 do CPF para segurança',
  `cpf_encrypted` VARCHAR(255) NULL DEFAULT NULL COMMENT 'CPF criptografado (reversível) para uso operacional',
  `data_expiracao_hash_cpf` DATE NULL DEFAULT NULL COMMENT 'Data para renovação do hash do CPF',
  `data_nascimento` DATE NOT NULL,
  `consentimento_lgpd` TINYINT NOT NULL DEFAULT FALSE COMMENT 'Aceite do termo de consentimento LGPD',
  `data_consentimento_lgpd` DATETIME NULL DEFAULT NULL COMMENT 'Data e hora do consentimento LGPD',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX (`cpf_hash` ASC) VISIBLE,
  INDEX `idx_pessoa_cpf_hash` (`cpf_hash` ASC) VISIBLE,
  INDEX `idx_pessoa_nome` (`nome` ASC) VISIBLE,
  INDEX `idx_pessoa_consentimento` (`consentimento_lgpd` ASC) VISIBLE,
  INDEX `idx_pessoa_data_nascimento` (`data_nascimento` ASC) VISIBLE)
COMMENT = 'Dados pessoais dos usuários do sistema - LGPD compliant';


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `perfil_acesso_id` INT NOT NULL,
  `status_usuario_id` TINYINT NOT NULL,
  `algoritmo_cripto_id` TINYINT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL COMMENT 'Hash da senha com salt',
  `tentativas_login_falhas` TINYINT NULL DEFAULT 0,
  `bloqueado_ate` TIMESTAMP NULL DEFAULT NULL,
  `data_ultimo_acesso` TIMESTAMP NULL DEFAULT NULL,
  `data_expiracao_senha` DATE NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  UNIQUE INDEX (`login` ASC) VISIBLE,
  INDEX `idx_usuario_pessoa` (`id_pessoa` ASC) VISIBLE,
  INDEX `idx_usuario_perfil` (`perfil_acesso_id` ASC) VISIBLE,
  INDEX `idx_usuario_status` (`status_usuario_id` ASC) VISIBLE,
  INDEX `idx_usuario_login` (`login` ASC) VISIBLE,
  INDEX `idx_usuario_email` (`email` ASC) VISIBLE,
  INDEX `idx_usuario_perfil_status` (`perfil_acesso_id` ASC, `status_usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_pessoa` (`id_pessoa` ASC) VISIBLE,
  INDEX `fk_usuario_perfil` (`perfil_acesso_id` ASC) VISIBLE,
  INDEX `fk_usuario_status` (`status_usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_algoritmo` (`algoritmo_cripto_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_acesso_id`)
    REFERENCES `mydb`.`perfil_acesso` (`id_perfil_acesso`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_status`
    FOREIGN KEY (`status_usuario_id`)
    REFERENCES `mydb`.`status_usuario` (`id_status`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_algoritmo`
    FOREIGN KEY (`algoritmo_cripto_id`)
    REFERENCES `mydb`.`algoritmo_cripto` (`id_algoritmo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Usuários com acesso ao sistema';


-- -----------------------------------------------------
-- Table `mydb`.`contato_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contato_usuario` (
  `id_contato_usuario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `tipo_contato_id` TINYINT NOT NULL,
  `valor_contato` VARCHAR(255) NOT NULL,
  `principal` TINYINT NULL DEFAULT FALSE,
  `verificado` TINYINT NULL DEFAULT FALSE,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_contato_usuario`),
  INDEX `idx_contato_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_contato_tipo` (`tipo_contato_id` ASC) VISIBLE,
  INDEX `idx_contato_principal` (`principal` ASC) VISIBLE,
  INDEX `fk_contato_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_contato_tipo` (`tipo_contato_id` ASC) VISIBLE,
  CONSTRAINT `fk_contato_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contato_tipo`
    FOREIGN KEY (`tipo_contato_id`)
    REFERENCES `mydb`.`tipo_contato` (`id_tipo_contato`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Contatos dos usuários (emails secundários, telefones, etc)';


-- -----------------------------------------------------
-- Table `mydb`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`email` (
  `id_email` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_email`),
  INDEX `idx_email_address` (`email` ASC) VISIBLE)
COMMENT = 'Endereços de email dos usuários';


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `id_telefone` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo` ENUM('celular', 'residencial', 'comercial') NULL DEFAULT 'celular',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_telefone`),
  INDEX `idx_telefone_numero` (`telefone` ASC) VISIBLE)
COMMENT = 'Números de telefone dos usuários';


-- -----------------------------------------------------
-- Table `mydb`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plano` (
  `id_plano` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_plano` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `valor_atual` DECIMAL(10,2) NOT NULL COMMENT 'Valor atual do plano em reais',
  `id_tipo_plano` TINYINT NOT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_plano`),
  INDEX `idx_plano_ativo` (`ativo` ASC) VISIBLE,
  INDEX `idx_plano_tipo` (`id_tipo_plano` ASC) VISIBLE,
  INDEX `fk_plano_tipo` (`id_tipo_plano` ASC) VISIBLE,
  CONSTRAINT `fk_plano_tipo`
    FOREIGN KEY (`id_tipo_plano`)
    REFERENCES `mydb`.`tipo_plano` (`id_tipo_plano`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Planos de assinatura da academia';


-- -----------------------------------------------------
-- Table `mydb`.`api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api` (
  `id_api` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(100) NOT NULL,
  `chave_api_encrypted` VARCHAR(512) NOT NULL COMMENT 'Chave API criptografada (AES-256)',
  `nivel_acesso` ENUM('basico', 'intermediario', 'avancado', 'admin') NOT NULL,
  `data_criacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_expiracao` DATE NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_api`),
  INDEX `idx_api_ativo` (`ativo` ASC) VISIBLE,
  INDEX `idx_api_expiracao` (`data_expiracao` ASC) VISIBLE)
COMMENT = 'Configurações de integração com APIs externas';


-- -----------------------------------------------------
-- Table `mydb`.`pulseira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pulseira` (
  `id_pulseira` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `codigo_dispositivo` VARCHAR(100) NOT NULL COMMENT 'Identificador único do dispositivo',
  `id_modelo_pulseira` TINYINT NOT NULL,
  `data_aquisicao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_api` INT NOT NULL,
  `id_status_pulseira` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pulseira`),
  UNIQUE INDEX (`codigo_dispositivo` ASC) VISIBLE,
  INDEX `idx_pulseira_status` (`id_status_pulseira` ASC) VISIBLE,
  INDEX `idx_pulseira_codigo` (`codigo_dispositivo` ASC) VISIBLE,
  INDEX `idx_pulseira_modelo` (`id_modelo_pulseira` ASC) VISIBLE,
  INDEX `fk_pulseira_modelo` (`id_modelo_pulseira` ASC) VISIBLE,
  INDEX `fk_pulseira_api` (`id_api` ASC) VISIBLE,
  INDEX `fk_pulseira_status` (`id_status_pulseira` ASC) VISIBLE,
  CONSTRAINT `fk_pulseira_modelo`
    FOREIGN KEY (`id_modelo_pulseira`)
    REFERENCES `mydb`.`modelo_pulseira` (`id_modelo_pulseira`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pulseira_api`
    FOREIGN KEY (`id_api`)
    REFERENCES `mydb`.`api` (`id_api`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pulseira_status`
    FOREIGN KEY (`id_status_pulseira`)
    REFERENCES `mydb`.`status_pulseira` (`id_status_pulseira`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Dispositivos de monitoramento de treino';


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `id_aluno` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `data_matricula` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `id_pulseira` INT NULL DEFAULT NULL,
  `id_status_aluno` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_aluno`),
  INDEX `idx_aluno_pessoa` (`id_pessoa` ASC) VISIBLE,
  INDEX `idx_aluno_status` (`id_status_aluno` ASC) VISIBLE,
  INDEX `idx_aluno_pulseira` (`id_pulseira` ASC) VISIBLE,
  INDEX `idx_aluno_pessoa_status` (`id_pessoa` ASC, `id_status_aluno` ASC) VISIBLE,
  INDEX `fk_aluno_pessoa` (`id_pessoa` ASC) VISIBLE,
  INDEX `fk_aluno_pulseira` (`id_pulseira` ASC) VISIBLE,
  INDEX `fk_aluno_status` (`id_status_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aluno_pulseira`
    FOREIGN KEY (`id_pulseira`)
    REFERENCES `mydb`.`pulseira` (`id_pulseira`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aluno_status`
    FOREIGN KEY (`id_status_aluno`)
    REFERENCES `mydb`.`status_aluno` (`id_status_aluno`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Alunos matriculados na academia';


-- -----------------------------------------------------
-- Table `mydb`.`historico_assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico_assinatura` (
  `id_historico_assinatura` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `id_plano` INT NOT NULL,
  `valor_plano_na_adesao` DECIMAL(10,2) NOT NULL COMMENT 'Valor histórico do plano',
  `data_inicio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_fim` DATETIME NULL DEFAULT NULL COMMENT 'Data de término ou cancelamento',
  `ativo` TINYINT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_historico_assinatura`),
  INDEX `idx_historico_aluno` (`id_aluno` ASC) VISIBLE,
  INDEX `idx_historico_plano` (`id_plano` ASC) VISIBLE,
  INDEX `idx_historico_ativo` (`ativo` ASC) VISIBLE,
  INDEX `idx_historico_datas` (`data_inicio` ASC, `data_fim` ASC) VISIBLE,
  INDEX `fk_historico_aluno` (`id_aluno` ASC) VISIBLE,
  INDEX `fk_historico_plano` (`id_plano` ASC) VISIBLE,
  CONSTRAINT `fk_historico_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`aluno` (`id_aluno`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_historico_plano`
    FOREIGN KEY (`id_plano`)
    REFERENCES `mydb`.`plano` (`id_plano`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Histórico de assinaturas com preços preservados';


-- -----------------------------------------------------
-- Table `mydb`.`restricao_medica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restricao_medica` (
  `id_restricao_medica` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `descricao` TEXT NOT NULL,
  `id_tipo_restricao` TINYINT NULL DEFAULT NULL,
  `id_gravidade` TINYINT NOT NULL,
  `data_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_restricao_medica`),
  INDEX `idx_restricao_aluno` (`id_aluno` ASC) VISIBLE,
  INDEX `idx_restricao_gravidade` (`id_gravidade` ASC) VISIBLE,
  INDEX `idx_restricao_tipo` (`id_tipo_restricao` ASC) VISIBLE,
  INDEX `fk_restricao_aluno` (`id_aluno` ASC) VISIBLE,
  INDEX `fk_restricao_tipo` (`id_tipo_restricao` ASC) VISIBLE,
  INDEX `fk_restricao_gravidade` (`id_gravidade` ASC) VISIBLE,
  CONSTRAINT `fk_restricao_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`aluno` (`id_aluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_restricao_tipo`
    FOREIGN KEY (`id_tipo_restricao`)
    REFERENCES `mydb`.`tipo_restricao` (`id_tipo_restricao`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_restricao_gravidade`
    FOREIGN KEY (`id_gravidade`)
    REFERENCES `mydb`.`gravidade_restricao` (`id_gravidade`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Restrições médicas e condições de saúde dos alunos';


-- -----------------------------------------------------
-- Table `mydb`.`sessao_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sessao_treino` (
  `id_sessao_treino` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_pulseira` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `hora_fim` TIME NULL DEFAULT NULL,
  `intensidade_media` SMALLINT NULL DEFAULT NULL COMMENT 'Intensidade média do treino (0-100)',
  `frequencia_cardiaca_media` SMALLINT NULL DEFAULT NULL,
  `calorias_queimadas` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_sessao_treino`),
  INDEX `idx_sessao_pulseira` (`id_pulseira` ASC) VISIBLE,
  INDEX `idx_sessao_data_inicio` (`data_inicio` ASC) VISIBLE,
  INDEX `idx_sessao_periodo` (`data_inicio` ASC, `data_fim` ASC) VISIBLE,
  INDEX `fk_sessao_pulseira` (`id_pulseira` ASC) VISIBLE,
  CONSTRAINT `fk_sessao_pulseira`
    FOREIGN KEY (`id_pulseira`)
    REFERENCES `mydb`.`pulseira` (`id_pulseira`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Registros de sessões de treino monitoradas';


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao_fisica` (
  `id_avaliacao_fisica` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_aluno` INT NOT NULL,
  `data_avaliacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `peso` DECIMAL(5,2) NOT NULL,
  `altura` DECIMAL(3,2) NULL DEFAULT NULL,
  `imc` DECIMAL(4,2) NULL DEFAULT NULL COMMENT 'Índice de Massa Corporal calculado',
  `percentual_gordura` DECIMAL(4,2) NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `avaliador` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_avaliacao_fisica`),
  INDEX `idx_avaliacao_aluno` (`id_aluno` ASC) VISIBLE,
  INDEX `idx_avaliacao_data` (`data_avaliacao` ASC) VISIBLE,
  INDEX `fk_avaliacao_aluno` (`id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`aluno` (`id_aluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = 'Avaliações físicas e antropométricas dos alunos';


-- -----------------------------------------------------
-- Table `mydb`.`medida_corporal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medida_corporal` (
  `id_medida_corporal` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_medida` VARCHAR(100) NOT NULL,
  `unidade_medida` VARCHAR(20) NOT NULL DEFAULT 'cm',
  `descricao` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_medida_corporal`),
  UNIQUE INDEX (`nome_medida` ASC) VISIBLE)
COMMENT = 'Catálogo de tipos de medidas corporais';


-- -----------------------------------------------------
-- Table `mydb`.`termo_consentimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`termo_consentimento` (
  `id_termo_consentimento` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `tipo_consentimento` VARCHAR(100) NOT NULL,
  `finalidade` TEXT NOT NULL,
  `versao_termo` VARCHAR(20) NOT NULL,
  `hash_conteudo` VARCHAR(255) NOT NULL COMMENT 'Hash do conteúdo para verificar alterações',
  `data_emissao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ativo` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`id_termo_consentimento`),
  UNIQUE INDEX `uk_tipo_versao` (`tipo_consentimento` ASC, `versao_termo` ASC) VISIBLE,
  INDEX `idx_termo_tipo` (`tipo_consentimento` ASC) VISIBLE,
  INDEX `idx_termo_ativo` (`ativo` ASC) VISIBLE)
COMMENT = 'Versões dos termos de consentimento LGPD';


-- -----------------------------------------------------
-- Table `mydb`.`consentimento_lgpd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consentimento_lgpd` (
  `id_consentimento_lgpd` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `termo_consentimento_id` INT NOT NULL,
  `consentimento_concedido` TINYINT NOT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `data_consentimento` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_revogacao` TIMESTAMP NULL DEFAULT NULL,
  `ativo` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`id_consentimento_lgpd`),
  INDEX `idx_consentimento_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_consentimento_termo` (`termo_consentimento_id` ASC) VISIBLE,
  INDEX `idx_consentimento_ativo` (`ativo` ASC) VISIBLE,
  INDEX `idx_consentimento_usuario_ativo` (`usuario_id` ASC, `ativo` ASC) VISIBLE,
  INDEX `fk_consentimento_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_consentimento_termo` (`termo_consentimento_id` ASC) VISIBLE,
  CONSTRAINT `fk_consentimento_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_consentimento_termo`
    FOREIGN KEY (`termo_consentimento_id`)
    REFERENCES `mydb`.`termo_consentimento` (`id_termo_consentimento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Registro de consentimentos LGPD por usuário';


-- -----------------------------------------------------
-- Table `mydb`.`sessao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sessao_usuario` (
  `id_sessao_usuario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `token_sessao` VARCHAR(255) NOT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` VARCHAR(512) NULL DEFAULT NULL,
  `ativa` TINYINT NULL DEFAULT TRUE,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_expiracao` TIMESTAMP NOT NULL,
  `data_ultimo_acesso` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_sessao_usuario`),
  UNIQUE INDEX (`token_sessao` ASC) VISIBLE,
  INDEX `idx_sessao_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_sessao_token` (`token_sessao` ASC) VISIBLE,
  INDEX `idx_sessao_ativa` (`ativa` ASC) VISIBLE,
  INDEX `idx_sessao_expiracao` (`data_expiracao` ASC) VISIBLE,
  INDEX `idx_sessao_usuario_ativa` (`usuario_id` ASC, `ativa` ASC, `data_expiracao` ASC) VISIBLE,
  INDEX `fk_sessao_usuario` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_sessao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = 'Controle de sessões ativas dos usuários';


-- -----------------------------------------------------
-- Table `mydb`.`log_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_acesso` (
  `id_log_acesso` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL DEFAULT NULL,
  `tipo_acesso_id` SMALLINT NOT NULL,
  `login_tentativa` VARCHAR(100) NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` VARCHAR(512) NULL DEFAULT NULL,
  `localizacao` VARCHAR(255) NULL DEFAULT NULL,
  `mensagem` TEXT NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log_acesso`),
  INDEX `idx_log_acesso_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_log_acesso_tipo` (`tipo_acesso_id` ASC) VISIBLE,
  INDEX `idx_log_acesso_data` (`data_criacao` ASC) VISIBLE,
  INDEX `idx_log_acesso_ip` (`ip_address` ASC) VISIBLE,
  INDEX `fk_log_acesso_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_log_acesso_tipo` (`tipo_acesso_id` ASC) VISIBLE,
  CONSTRAINT `fk_log_acesso_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_log_acesso_tipo`
    FOREIGN KEY (`tipo_acesso_id`)
    REFERENCES `mydb`.`tipo_acesso` (`id_tipo_acesso`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Log de tentativas de acesso ao sistema';


-- -----------------------------------------------------
-- Table `mydb`.`log_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_sistema` (
  `id_log_sistema` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL DEFAULT NULL,
  `tipo_log_id` TINYINT NOT NULL,
  `categoria_id` SMALLINT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `mensagem` TEXT NULL DEFAULT NULL,
  `stack_trace` TEXT NULL DEFAULT NULL,
  `dados_contexto` JSON NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `url_origem` VARCHAR(500) NULL DEFAULT NULL,
  `metodo_http` VARCHAR(10) NULL DEFAULT NULL,
  `resolvido` TINYINT NULL DEFAULT FALSE,
  `data_resolucao` TIMESTAMP NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log_sistema`),
  INDEX `idx_log_sistema_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_log_sistema_tipo` (`tipo_log_id` ASC) VISIBLE,
  INDEX `idx_log_sistema_categoria` (`categoria_id` ASC) VISIBLE,
  INDEX `idx_log_sistema_data` (`data_criacao` ASC) VISIBLE,
  INDEX `idx_log_sistema_resolvido` (`resolvido` ASC) VISIBLE,
  INDEX `fk_log_sistema_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_log_sistema_tipo` (`tipo_log_id` ASC) VISIBLE,
  INDEX `fk_log_sistema_categoria` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_log_sistema_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_log_sistema_tipo`
    FOREIGN KEY (`tipo_log_id`)
    REFERENCES `mydb`.`tipo_log_sistema` (`id_tipo_log`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_log_sistema_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria_log_sistema` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Log de eventos e erros do sistema';


-- -----------------------------------------------------
-- Table `mydb`.`registro_auditavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro_auditavel` (
  `id_registro_auditavel` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `tabela_id` SMALLINT NOT NULL,
  `registro_pk_texto` VARCHAR(100) NOT NULL COMMENT 'PK do registro em formato texto',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_registro_auditavel`),
  UNIQUE INDEX `uk_registro_tabela_pk` (`tabela_id` ASC, `registro_pk_texto` ASC) VISIBLE,
  INDEX `idx_registro_tabela` (`tabela_id` ASC) VISIBLE,
  INDEX `fk_registro_tabela` (`tabela_id` ASC) VISIBLE,
  CONSTRAINT `fk_registro_tabela`
    FOREIGN KEY (`tabela_id`)
    REFERENCES `mydb`.`tabela_sistema` (`id_tabela`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = 'Índice de registros auditáveis';


-- -----------------------------------------------------
-- Table `mydb`.`log_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_auditoria` (
  `id_log_auditoria` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL DEFAULT NULL,
  `registro_auditavel_id` BIGINT NULL DEFAULT NULL,
  `tipo_operacao_id` TINYINT NOT NULL,
  `dados_anteriores` JSON NULL DEFAULT NULL COMMENT 'Estado anterior do registro (UPDATE/DELETE)',
  `dados_novos` JSON NULL DEFAULT NULL COMMENT 'Estado novo do registro (INSERT/UPDATE)',
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `justificativa` TEXT NULL DEFAULT NULL COMMENT 'Justificativa da operação quando aplicável',
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log_auditoria`),
  INDEX `idx_log_auditoria_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_log_auditoria_registro` (`registro_auditavel_id` ASC) VISIBLE,
  INDEX `idx_log_auditoria_tipo` (`tipo_operacao_id` ASC) VISIBLE,
  INDEX `idx_log_auditoria_data` (`data_criacao` ASC) VISIBLE,
  INDEX `idx_log_auditoria_data_usuario` (`data_criacao` ASC, `usuario_id` ASC) VISIBLE,
  INDEX `fk_log_auditoria_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_log_auditoria_registro` (`registro_auditavel_id` ASC) VISIBLE,
  INDEX `fk_log_auditoria_tipo` (`tipo_operacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_log_auditoria_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_log_auditoria_registro`
    FOREIGN KEY (`registro_auditavel_id`)
    REFERENCES `mydb`.`registro_auditavel` (`id_registro_auditavel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_log_auditoria_tipo`
    FOREIGN KEY (`tipo_operacao_id`)
    REFERENCES `mydb`.`tipo_operacao_auditoria` (`id_tipo_operacao`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
COMMENT = 'Log de auditoria completo para rastreamento de alterações';


-- -----------------------------------------------------
-- Table `mydb`.`pessoa_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa_email` (
  `id_pessoa` INT NOT NULL,
  `id_email` INT NOT NULL,
  `principal` TINYINT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pessoa`, `id_email`),
  INDEX `fk_pessoa_email_email` (`id_email` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_email_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pessoa_email_email`
    FOREIGN KEY (`id_email`)
    REFERENCES `mydb`.`email` (`id_email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`pessoa_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa_telefone` (
  `id_pessoa` INT NOT NULL,
  `id_telefone` INT NOT NULL,
  `principal` TINYINT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pessoa`, `id_telefone`),
  INDEX `fk_pessoa_telefone_telefone` (`id_telefone` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_telefone_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id_pessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pessoa_telefone_telefone`
    FOREIGN KEY (`id_telefone`)
    REFERENCES `mydb`.`telefone` (`id_telefone`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao_medida` (
  `id_avaliacao_fisica` INT NOT NULL,
  `id_medida_corporal` INT NOT NULL,
  `valor_medida` DECIMAL(6,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_avaliacao_fisica`, `id_medida_corporal`),
  INDEX `fk_avaliacao_medida_medida` (`id_medida_corporal` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_medida_avaliacao`
    FOREIGN KEY (`id_avaliacao_fisica`)
    REFERENCES `mydb`.`avaliacao_fisica` (`id_avaliacao_fisica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_avaliacao_medida_medida`
    FOREIGN KEY (`id_medida_corporal`)
    REFERENCES `mydb`.`medida_corporal` (`id_medida_corporal`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`aluno_sessao_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_sessao_treino` (
  `id_aluno` INT NOT NULL,
  `id_sessao_treino` INT NOT NULL,
  `id_tipo_treino` TINYINT NULL DEFAULT NULL,
  `objetivo` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_aluno`, `id_sessao_treino`),
  INDEX `idx_aluno_sessao_tipo` (`id_tipo_treino` ASC) VISIBLE,
  INDEX `fk_aluno_sessao_treino` (`id_sessao_treino` ASC) VISIBLE,
  INDEX `fk_aluno_sessao_tipo_treino` (`id_tipo_treino` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_sessao_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`aluno` (`id_aluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aluno_sessao_treino`
    FOREIGN KEY (`id_sessao_treino`)
    REFERENCES `mydb`.`sessao_treino` (`id_sessao_treino`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aluno_sessao_tipo_treino`
    FOREIGN KEY (`id_tipo_treino`)
    REFERENCES `mydb`.`tipo_treino` (`id_tipo_treino`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`v_alunos_ativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`v_alunos_ativos` (`id_aluno` INT, `nome` INT, `data_nascimento` INT, `status` INT, `nome_plano` INT, `valor_plano_na_adesao` INT, `data_inicio_plano` INT, `data_fim_plano` INT, `data_matricula` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`v_restricoes_criticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`v_restricoes_criticas` (`nome_aluno` INT, `restricao` INT, `tipo` INT, `gravidade` INT, `data_registro` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`v_pulseiras_uso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`v_pulseiras_uso` (`codigo_dispositivo` INT, `modelo` INT, `status` INT, `aluno_atual` INT, `data_aquisicao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`v_usuarios_ativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`v_usuarios_ativos` (`id_usuario` INT, `nome` INT, `email` INT, `login` INT, `nome_perfil` INT, `nome_status` INT, `data_ultimo_acesso` INT, `data_criacao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`v_sessoes_ativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`v_sessoes_ativas` (`id_sessao_usuario` INT, `login` INT, `nome` INT, `ip_address` INT, `data_criacao` INT, `data_expiracao` INT, `data_ultimo_acesso` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`v_auditoria_recente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`v_auditoria_recente` (`id_log_auditoria` INT, `usuario` INT, `nome_tabela` INT, `registro_pk_texto` INT, `operacao` INT, `ip_address` INT, `data_criacao` INT);

-- -----------------------------------------------------
-- procedure sp_nova_assinatura
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
-- Procedure: Registrar nova assinatura de plano
CREATE PROCEDURE sp_nova_assinatura(
    IN p_id_aluno INT,
    IN p_id_plano INT
)
BEGIN
    DECLARE v_valor_atual DECIMAL(10,2);
    
    SELECT valor_atual INTO v_valor_atual
    FROM plano
    WHERE id_plano = p_id_plano AND ativo = TRUE;
    
    UPDATE historico_assinatura
    SET ativo = FALSE, data_fim = CURRENT_TIMESTAMP
    WHERE id_aluno = p_id_aluno AND ativo = TRUE;
    
    INSERT INTO historico_assinatura (id_aluno, id_plano, valor_plano_na_adesao, data_inicio, ativo)
    VALUES (p_id_aluno, p_id_plano, v_valor_atual, CURRENT_TIMESTAMP, TRUE);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_registrar_tentativa_login
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE sp_registrar_tentativa_login(
    IN p_login VARCHAR(100),
    IN p_sucesso BOOLEAN,
    IN p_ip VARCHAR(45),
    IN p_user_agent VARCHAR(512)
)
BEGIN
    DECLARE v_usuario_id INT;
    DECLARE v_tipo_acesso_id SMALLINT;
    
    SELECT id_usuario INTO v_usuario_id
    FROM usuario WHERE login = p_login;
    
    IF p_sucesso THEN
        SELECT id_tipo_acesso INTO v_tipo_acesso_id
        FROM tipo_acesso WHERE nome_tipo = 'Login Sucesso';
        
        IF v_usuario_id IS NOT NULL THEN
            UPDATE usuario 
            SET tentativas_login_falhas = 0,
                bloqueado_ate = NULL,
                data_ultimo_acesso = CURRENT_TIMESTAMP
            WHERE id_usuario = v_usuario_id;
        END IF;
    ELSE
        SELECT id_tipo_acesso INTO v_tipo_acesso_id
        FROM tipo_acesso WHERE nome_tipo = 'Login Falha';
        
        IF v_usuario_id IS NOT NULL THEN
            UPDATE usuario 
            SET tentativas_login_falhas = tentativas_login_falhas + 1
            WHERE id_usuario = v_usuario_id;
            
            IF (SELECT tentativas_login_falhas FROM usuario WHERE id_usuario = v_usuario_id) >= 5 THEN
                UPDATE usuario 
                SET bloqueado_ate = DATE_ADD(NOW(), INTERVAL 30 MINUTE)
                WHERE id_usuario = v_usuario_id;
            END IF;
        END IF;
    END IF;
    
    INSERT INTO log_acesso (usuario_id, tipo_acesso_id, login_tentativa, ip_address, user_agent)
    VALUES (v_usuario_id, v_tipo_acesso_id, p_login, p_ip, p_user_agent);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_criar_sessao
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE sp_criar_sessao(
    IN p_usuario_id INT,
    IN p_token VARCHAR(255),
    IN p_ip VARCHAR(45),
    IN p_user_agent VARCHAR(512),
    IN p_duracao_horas INT
)
BEGIN
    INSERT INTO sessao_usuario (
        usuario_id,
        token_sessao,
        ip_address,
        user_agent,
        data_expiracao
    ) VALUES (
        p_usuario_id,
        p_token,
        p_ip,
        p_user_agent,
        DATE_ADD(NOW(), INTERVAL p_duracao_horas HOUR)
    );
    
    SELECT LAST_INSERT_ID() as id_sessao;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_validar_sessao
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE sp_validar_sessao(
    IN p_token VARCHAR(255),
    OUT p_valida BOOLEAN,
    OUT p_usuario_id INT
)
BEGIN
    DECLARE v_count INT;
    
    SELECT COUNT(*), usuario_id INTO v_count, p_usuario_id
    FROM sessao_usuario
    WHERE token_sessao = p_token
      AND ativa = TRUE
      AND data_expiracao > NOW()
    GROUP BY usuario_id;
    
    SET p_valida = (v_count > 0);
    
    IF p_valida THEN
        UPDATE sessao_usuario 
        SET data_ultimo_acesso = CURRENT_TIMESTAMP
        WHERE token_sessao = p_token;
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_registrar_auditoria
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE sp_registrar_auditoria(
    IN p_usuario_id INT,
    IN p_nome_tabela VARCHAR(100),
    IN p_registro_pk VARCHAR(100),
    IN p_operacao VARCHAR(30),
    IN p_dados_anteriores JSON,
    IN p_dados_novos JSON,
    IN p_ip VARCHAR(45),
    IN p_justificativa TEXT
)
BEGIN
    DECLARE v_tabela_id SMALLINT;
    DECLARE v_registro_id BIGINT;
    DECLARE v_operacao_id TINYINT;
    
    SELECT id_tabela INTO v_tabela_id
    FROM tabela_sistema WHERE nome_tabela = p_nome_tabela;
    
    SELECT id_tipo_operacao INTO v_operacao_id
    FROM tipo_operacao_auditoria WHERE nome_operacao = p_operacao;
    
    INSERT INTO registro_auditavel (tabela_id, registro_pk_texto)
    VALUES (v_tabela_id, p_registro_pk)
    ON DUPLICATE KEY UPDATE id_registro_auditavel = LAST_INSERT_ID(id_registro_auditavel);
    
    SET v_registro_id = LAST_INSERT_ID();
    
    INSERT INTO log_auditoria (
        usuario_id,
        registro_auditavel_id,
        tipo_operacao_id,
        dados_anteriores,
        dados_novos,
        ip_address,
        justificativa
    ) VALUES (
        p_usuario_id,
        v_registro_id,
        v_operacao_id,
        p_dados_anteriores,
        p_dados_novos,
        p_ip,
        p_justificativa
    );
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_verificar_consentimento_lgpd
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE sp_verificar_consentimento_lgpd(
    IN p_id_usuario INT,
    OUT p_tem_consentimento BOOLEAN,
    OUT p_data_consentimento DATETIME
)
BEGIN
    SELECT 
        COALESCE(MAX(consentimento_concedido), FALSE),
        MAX(data_consentimento)
    INTO p_tem_consentimento, p_data_consentimento
    FROM consentimento_lgpd
    WHERE usuario_id = p_id_usuario
      AND ativo = TRUE;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_relatorio_treinos
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE sp_relatorio_treinos(
    IN p_id_aluno INT,
    IN p_data_inicio DATE,
    IN p_data_fim DATE
)
BEGIN
    SELECT 
        st.data_inicio,
        st.hora_inicio,
        st.data_fim,
        st.hora_fim,
        tt.nome_tipo AS tipo_treino,
        st.intensidade_media,
        st.frequencia_cardiaca_media,
        st.calorias_queimadas,
        ast.objetivo
    FROM sessao_treino st
    INNER JOIN aluno_sessao_treino ast ON st.id_sessao_treino = ast.id_sessao_treino
    LEFT JOIN tipo_treino tt ON ast.id_tipo_treino = tt.id_tipo_treino
    WHERE ast.id_aluno = p_id_aluno
      AND st.data_inicio BETWEEN p_data_inicio AND p_data_fim
    ORDER BY st.data_inicio DESC, st.hora_inicio DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_expirar_sessoes_antigas
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE sp_expirar_sessoes_antigas()
BEGIN
    UPDATE sessao_usuario
    SET ativa = FALSE
    WHERE data_expiracao < NOW() AND ativa = TRUE;
    
    SELECT ROW_COUNT() as sessoes_expiradas;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_limpar_logs_antigos
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE sp_limpar_logs_antigos(
    IN p_dias_retencao INT
)
BEGIN
    DECLARE v_data_limite DATETIME;
    SET v_data_limite = DATE_SUB(NOW(), INTERVAL p_dias_retencao DAY);
    
    -- Limpar logs de acesso antigos
    DELETE FROM log_acesso WHERE data_criacao < v_data_limite;
    
    -- Limpar logs de sistema resolvidos antigos
    DELETE FROM log_sistema 
    WHERE data_criacao < v_data_limite AND resolvido = TRUE;
    
    -- Limpar sessões expiradas antigas
    DELETE FROM sessao_usuario 
    WHERE data_criacao < v_data_limite AND ativa = FALSE;
    
    SELECT 
        'Logs antigos removidos com sucesso' as mensagem,
        p_dias_retencao as dias_retencao,
        v_data_limite as data_limite;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function fn_usuario_bloqueado
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE FUNCTION fn_usuario_bloqueado(p_id_usuario INT)
RETURNS BOOLEAN
READS SQL DATA
BEGIN
    DECLARE v_bloqueado_ate TIMESTAMP;
    
    SELECT bloqueado_ate INTO v_bloqueado_ate
    FROM usuario
    WHERE id_usuario = p_id_usuario;
    
    IF v_bloqueado_ate IS NULL THEN
        RETURN FALSE;
    END IF;
    
    RETURN (v_bloqueado_ate > NOW());
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function fn_sessao_valida
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE FUNCTION fn_sessao_valida(p_token VARCHAR(255))
RETURNS BOOLEAN
READS SQL DATA
BEGIN
    DECLARE v_count INT;
    
    SELECT COUNT(*) INTO v_count
    FROM sessao_usuario
    WHERE token_sessao = p_token
      AND ativa = TRUE
      AND data_expiracao > NOW();
    
    RETURN (v_count > 0);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function fn_usuario_tem_permissao
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE FUNCTION fn_usuario_tem_permissao(
    p_id_usuario INT,
    p_modulo VARCHAR(50),
    p_acao VARCHAR(20)
)
RETURNS BOOLEAN
READS SQL DATA
BEGIN
    DECLARE v_count INT;
    
    SELECT COUNT(*) INTO v_count
    FROM usuario u
    INNER JOIN permissao_perfil pp ON u.perfil_acesso_id = pp.perfil_acesso_id
    WHERE u.id_usuario = p_id_usuario
      AND pp.modulo = p_modulo
      AND pp.acao = p_acao
      AND pp.ativo = TRUE;
    
    RETURN (v_count > 0);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function fn_tempo_sessao_minutos
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE FUNCTION fn_tempo_sessao_minutos(p_token VARCHAR(255))
RETURNS INT
READS SQL DATA
BEGIN
    DECLARE v_minutos INT;
    
    SELECT TIMESTAMPDIFF(MINUTE, data_criacao, data_ultimo_acesso)
    INTO v_minutos
    FROM sessao_usuario
    WHERE token_sessao = p_token;
    
    RETURN COALESCE(v_minutos, 0);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`v_alunos_ativos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`v_alunos_ativos`;
USE `mydb`;
CREATE OR REPLACE VIEW v_alunos_ativos AS
SELECT 
    a.id_aluno,
    p.nome,
    p.data_nascimento,
    sa.nome_status AS status,
    pl.nome_plano,
    ha.valor_plano_na_adesao,
    ha.data_inicio AS data_inicio_plano,
    ha.data_fim AS data_fim_plano,
    a.data_matricula
FROM aluno a
INNER JOIN pessoa p ON a.id_pessoa = p.id_pessoa
INNER JOIN status_aluno sa ON a.id_status_aluno = sa.id_status_aluno
LEFT JOIN historico_assinatura ha ON a.id_aluno = ha.id_aluno AND ha.ativo = TRUE
LEFT JOIN plano pl ON ha.id_plano = pl.id_plano
WHERE sa.nome_status = 'Ativo';

-- -----------------------------------------------------
-- View `mydb`.`v_restricoes_criticas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`v_restricoes_criticas`;
USE `mydb`;
CREATE OR REPLACE VIEW v_restricoes_criticas AS
SELECT 
    p.nome AS nome_aluno,
    rm.descricao AS restricao,
    tr.nome_tipo AS tipo,
    gr.nivel AS gravidade,
    rm.data_registro
FROM restricao_medica rm
INNER JOIN aluno a ON rm.id_aluno = a.id_aluno
INNER JOIN pessoa p ON a.id_pessoa = p.id_pessoa
LEFT JOIN tipo_restricao tr ON rm.id_tipo_restricao = tr.id_tipo_restricao
INNER JOIN gravidade_restricao gr ON rm.id_gravidade = gr.id_gravidade
WHERE gr.ordem_prioridade >= 3
ORDER BY gr.ordem_prioridade DESC, rm.data_registro DESC;

-- -----------------------------------------------------
-- View `mydb`.`v_pulseiras_uso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`v_pulseiras_uso`;
USE `mydb`;
CREATE OR REPLACE VIEW v_pulseiras_uso AS
SELECT 
    pu.codigo_dispositivo,
    mp.nome_modelo AS modelo,
    sp.nome_status AS status,
    p.nome AS aluno_atual,
    pu.data_aquisicao
FROM pulseira pu
INNER JOIN modelo_pulseira mp ON pu.id_modelo_pulseira = mp.id_modelo_pulseira
INNER JOIN status_pulseira sp ON pu.id_status_pulseira = sp.id_status_pulseira
LEFT JOIN aluno a ON pu.id_pulseira = a.id_pulseira
LEFT JOIN pessoa p ON a.id_pessoa = p.id_pessoa;

-- -----------------------------------------------------
-- View `mydb`.`v_usuarios_ativos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`v_usuarios_ativos`;
USE `mydb`;
CREATE OR REPLACE VIEW v_usuarios_ativos AS
SELECT 
    u.id_usuario,
    p.nome,
    u.email,
    u.login,
    pa.nome_perfil,
    su.nome_status,
    u.data_ultimo_acesso,
    u.data_criacao
FROM usuario u
INNER JOIN pessoa p ON u.id_pessoa = p.id_pessoa
INNER JOIN perfil_acesso pa ON u.perfil_acesso_id = pa.id_perfil_acesso
INNER JOIN status_usuario su ON u.status_usuario_id = su.id_status
WHERE su.nome_status = 'Ativo';

-- -----------------------------------------------------
-- View `mydb`.`v_sessoes_ativas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`v_sessoes_ativas`;
USE `mydb`;
CREATE OR REPLACE VIEW v_sessoes_ativas AS
SELECT 
    s.id_sessao_usuario,
    u.login,
    p.nome,
    s.ip_address,
    s.data_criacao,
    s.data_expiracao,
    s.data_ultimo_acesso
FROM sessao_usuario s
INNER JOIN usuario u ON s.usuario_id = u.id_usuario
INNER JOIN pessoa p ON u.id_pessoa = p.id_pessoa
WHERE s.ativa = TRUE 
  AND s.data_expiracao > NOW();

-- -----------------------------------------------------
-- View `mydb`.`v_auditoria_recente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`v_auditoria_recente`;
USE `mydb`;
CREATE OR REPLACE VIEW v_auditoria_recente AS
SELECT 
    la.id_log_auditoria,
    u.login AS usuario,
    ts.nome_tabela,
    ra.registro_pk_texto,
    to_op.nome_operacao AS operacao,
    la.ip_address,
    la.data_criacao
FROM log_auditoria la
LEFT JOIN usuario u ON la.usuario_id = u.id_usuario
INNER JOIN registro_auditavel ra ON la.registro_auditavel_id = ra.id_registro_auditavel
INNER JOIN tabela_sistema ts ON ra.tabela_id = ts.id_tabela
INNER JOIN tipo_operacao_auditoria to_op ON la.tipo_operacao_id = to_op.id_tipo_operacao
ORDER BY la.data_criacao DESC
LIMIT 100;
USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE TRIGGER before_insert_pessoa_lgpd
BEFORE INSERT ON pessoa
FOR EACH ROW
BEGIN
    IF NEW.consentimento_lgpd = TRUE AND NEW.data_consentimento_lgpd IS NULL THEN
        SET NEW.data_consentimento_lgpd = CURRENT_TIMESTAMP;
    END IF;
END$$

USE `mydb`$$
CREATE TRIGGER before_update_pessoa_lgpd
BEFORE UPDATE ON pessoa
FOR EACH ROW
BEGIN
    IF NEW.consentimento_lgpd = TRUE AND OLD.consentimento_lgpd = FALSE THEN
        SET NEW.data_consentimento_lgpd = CURRENT_TIMESTAMP;
    END IF;
END$$

USE `mydb`$$
CREATE TRIGGER after_update_usuario_acesso
AFTER UPDATE ON usuario
FOR EACH ROW
BEGIN
    IF NEW.data_ultimo_acesso > OLD.data_ultimo_acesso THEN
        UPDATE usuario 
        SET tentativas_login_falhas = 0, bloqueado_ate = NULL
        WHERE id_usuario = NEW.id_usuario;
    END IF;
END$$

USE `mydb`$$
-- Trigger: Cálculo de IMC antes de INSERT
CREATE TRIGGER before_insert_avaliacao_fisica
BEFORE INSERT ON avaliacao_fisica
FOR EACH ROW
BEGIN
    IF NEW.altura IS NOT NULL AND NEW.altura > 0 THEN
        SET NEW.imc = NEW.peso / (NEW.altura * NEW.altura);
    END IF;
END$$

USE `mydb`$$
CREATE TRIGGER before_update_avaliacao_fisica
BEFORE UPDATE ON avaliacao_fisica
FOR EACH ROW
BEGIN
    IF NEW.altura IS NOT NULL AND NEW.altura > 0 THEN
        SET NEW.imc = NEW.peso / (NEW.altura * NEW.altura);
    END IF;
END$$

USE `mydb`$$
CREATE TRIGGER before_insert_sessao_usuario
BEFORE INSERT ON sessao_usuario
FOR EACH ROW
BEGIN
    -- Inativar sessões antigas do mesmo usuário
    UPDATE sessao_usuario 
    SET ativa = FALSE 
    WHERE usuario_id = NEW.usuario_id AND ativa = TRUE;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
